services:
  nameserver:
    build: ./nameserver
    container_name: nameserver
    ports:
      - "8761:8761"
  admin:
    build: ./admin
    container_name: admin
    depends_on:
      - "nameserver"
    ports:
      - "8888:8888"