services:
  database:
    image: mysql:8.0
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: whatamiwatching
    volumes:
      - "./database/create.sql:/docker-entrypoint-initdb.d/1.sql"
  nameserver:
    build: ./nameserver
    container_name: nameserver
    ports:
      - "8761:8761"
  admin:
    build: ./admin
    container_name: admin
    depends_on:
      - "nameserver"
    ports:
      - "8888:8888"
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - "nameserver"
      - "admin"
    ports:
      - "8080:8080"
  user:
    build: ./user
    container_name: user
    depends_on:
      - "nameserver"
      - "admin"
      - "api-gateway"
      - "database"
    ports:
      - "8081:8081"
  movie:
    build: ./movie
    container_name: movie
    depends_on:
      - "nameserver"
      - "admin"
      - "api-gateway"
    ports:
      - "8082:8082"
  genre:
    build: ./genre
    container_name: genre
    depends_on:
      - "nameserver"
      - "admin"
      - "api-gateway"
      - "database"
    ports:
      - "8083:8083"