services:
  database:
    image: mysql:8.0
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: whatamiwatching
    volumes:
      - "./database/create.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: unless-stopped
  nameserver:
    build: ./nameserver
    container_name: nameserver
  admin:
    build: ./admin
    container_name: admin
    depends_on:
      - "nameserver"
    ports:
      - "8888:8888"
    restart: unless-stopped
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - "nameserver"
      - "admin"
    ports:
      - "8080:8080"
    restart: unless-stopped
  user:
    build: ./user
    container_name: user
    depends_on:
      - "nameserver"
      - "admin"
      - "api-gateway"
      - "database"
    restart: unless-stopped
  movie:
    build: ./movie
    container_name: movie
    depends_on:
      - "nameserver"
      - "admin"
      - "api-gateway"
    restart: unless-stopped
  genre:
    build: ./genre
    container_name: genre
    depends_on:
      - "nameserver"
      - "admin"
      - "api-gateway"
      - "database"
    restart: unless-stopped