spring:
  application:
    name: WAIW-GATEWAY
  boot:
    admin:
      client:
        url: http://admin:8888
  cloud:
    gateway:
      routes:
        - id: user_backend
          uri: lb://WAIW-USER
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/, /
        - id: movie_backend
          uri: lb://WAIW-MOVIE
          predicates:
            - Path=/api/movie/**
          filters:
            - RewritePath=/api/movie/, /
        - id: genre_backend
          uri: lb://WAIW-GENRE
          predicates:
            - Path=/api/genre/**
          filters:
            - RewritePath=/api/genre/, /
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://nameserver:8761/eureka
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
